# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

line-length = 120
indent-width = 4

# Assume Python 3.12
target-version = "py312"

[lint]
select = [
    "B",   # flake8-bugbear
    "C",   # flake8-comprehensions
    "D2",  # pydocstyle (D100-D499)
    "E",   # pycodestyle
    "F",   # pyflakes
    "W",   # flake8-warnings
    "I",   # isort
    "TID", # flake8-tidy-imports
]
# TODO: remove these as fast as possible
ignore = [
    "B006",
    "B007",
    "B008",
    "B018",
    "B019",
    "B023",
    "B026",
    "B904",
    "C416",
    "C419",
    "C901",
    "D203", # docstring style choice (incompatible with D211)
    "D205", # style choice: blank line after first line of multiline docstring
    "D212", # docstring style choice (incompatible with D213)
    "E266",
    "E501",
    "F403",
    "F405",
    "UP007", # prefer Union[X, Y] over X | Y
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

# Auto-formatting of code examples in docstrings (Markdown)
# Planned to be opt-out in future
docstring-code-format = false
docstring-code-line-length = "dynamic"
